### ISSUE TITLE
Zoom effect for RecyclerView 

### ISSUE THREAD

**Issue by amanzan** [surahul/Bounce#8]
Is it possible to achieve the effect that ScrollView and ListView have for RecyclerView?

Thanks!

**Comment by rv-vdev** [comment]
Yeah it is absolutely possible... Go to the samples and checkout yourself

**Comment by amanzan** [comment]
I tried, moving the code from ScrollView:

`BounceTouchListener.OnTranslateListener onTranslateListener = new BounceTouchListener.OnTranslateListener() {
            @Override
            public void onTranslate(float translation) {
                if (translation > 0) {
                    float scale = ((2 * translation) / header.getMeasuredHeight()) + 1;
                    header.setScaleX(scale);
                    header.setScaleY(scale);
                }
            }
        };`

But this is what I get:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3911627/20640581/4f73e5ba-b3e2-11e6-99d7-d5bece5bcaaa.gif)

**Comment by amanzan** [comment]
I got it right, by removing the pivot features
